= xenon(1)
Carson Graham
:doctype: manpage
:man manual: Xenon Manual
:man source: Xenon latest commit
:page-layout: base

== NAME
xenon - A natively compiled programming language similar to C

== SYNOPSIS

xenon [_OPTIONS_]... _FILE_

== DESCRIPTION

The xenon(1) command converts Xenon Source file _FILE_ into NASM assembly, object files, or x64/x86 machine code.
Single-character options __cannot__ be combined into the same block, ie `-fe`.

== OPTIONS

=== Generic Options

-V, --version::
  Print the version of the xenon compiler

-h, --help::
  Print this help menu

=== Compiler Options


-f __FORMAT__, --format __FORMAT__::
  __FORMAT__ must be one of the following: __NASM__, __OBJECT__, __NATIVE__, __RUN__.
  By default, it is native. __NASM__ will output only assembly (in NASM format).
  __OBJECT__ will output the assembly after it's been ran through the NASM command (see below).
  __NATIVE__ will run the object file through the gcc command, outputting a binary executable.
  __RUN__ will run the outputted binary executable after it is created.

--run::
  A shortcut for --format RUN

--nasm __NASM_COMMAND__::
  _NASM_COMMAND_ is a string which is ran through a find-replace and then executed.
  `{i}` is replaced by the input file name/path, in quotes,
  and `{o}` is replaced by the output file in the same way.
  This command is ran at in the _BUILD_DIR_/_FILENAME_ID_/ directory, so it may create files.
+
An example of this: `--nasm "nasm -felf64 {i} -o {o}"`

--gcc __GCC_COMMAND__::
  _GCC_COMMAND_ is similar to the _NASM_COMMAND_, but instead is the object file-to-binary command.
  It is ran in the same place as the __NASM_COMMAND__.
  Nothing is done between the two commands, if they are both scheduled to run.
+
As an example, `--gcc "gcc {i} -no-pie -o {o}"`

-b __BUILD_DIR__, --build __BUILD_DIR__::
  The directory to put intermediate build files into.

+
The build directory is organized into several folders to mirror the source file structure.
For each file, a directory is created with the name plus a tiny hashcode.
Inside that directory the source file, object file, and binary file are placed.

-t __TARGET__, --target __TARGET__::
  Where the resulting final binary should be named.
  Defaults to a reasonable value.

=== Optimization Options

-o__NAME__, --optimize __NAME__::
  Enables the optimisation with the name __NAME__.
  Possible values include _dead-code-elem_,
  _inline-macros_, _reshuffle_, _value-propagator_, and _flatten-typeless-blocks_
-ono__NAME__, --optimize no__NAME__::
  Disable the optimization with the name __NAME__.
  See above for options.
-O__N__, --optimization-level __N__::
  If __N__ is 0, no optimization is applied. The is the default.
  If __N__ is an integer between 1 and 10 inclusive,
  the default optimization settings are enabled and the optimizer is ran __N__
  passes over the AST.
+
__N__=3 is recommended for general development,
__N__=10 for release,
and __N__=0 for debugging the compiler.

=== Verbosity Options
-v, -v__NAME__, --verbose::
  Enables the verbose output titled __NAME__.

|===
| Flag | Description

| `-vend-timings` | Print how long it took to run and compile.
| `-vend-compile-timings` | Print how long each portion of the compiler took to run.
| `-voptimizations` | Print debug information about how each optimization was applied.
| `-vast` | Print both the non-optimized and optimized AST.
| `-vdecompile-ast` | Print a decompiled AST.
| `-vtokens` | Print the lexed tokens.
| `-vpurity` | Print the purity of each defined function.
| `-vall`, `-vv` | Print all of the above.
| `-v`, `--verbose` | Print a helpful subset of the above.
|===